### ISSUE TITLE
Part 1, Notebook 1: Contextualize Jupyter

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/Python-Fundamentals#1]
I think it'd be useful to have 2-3 sentences at the beginning of Header 1, "Working with Jupyter Notebooks" contextualizing the usage of a notebook. Specifically: we need an interface to begin coding, and we're opting to use Jupyter Notebooks for [insert short reason here].

**Comment by tomvannuenen** [comment]
Added a sentence to this effect.
