### ISSUE TITLE
Check 4/5/6 for introduction of vectorization in Pandas

### ISSUE THREAD

**Issue by tomvannuenen** [dlab-berkeley/Python-Fundamentals#10]
I removed the challenge in notebook 6 around the for-loop, as discussed. I now introduce vectorization in 4 and further build on it in 5 using examples.
Please check if you agree!

**Comment by pssachdeva** [comment]
This is in notebook 5, not 4, right? It looks good to me. I would change the header from "Looping over DataFrames?" to something referencing vectorizing and for loops. Maybe even "How I Learned to Stop For-Looping and Love the Vectorization" :joy:

**Comment by pssachdeva** [comment]
Should all the filepath concepts at the beginning of Notebook 6 be removed since we don't need a for loop there anymore?

**Comment by tomvannuenen** [comment]
I was thinking some info / a challenge on file paths would still be valuable, also because it means we can still include concatenation which I think is helpful. But agreed, it's not strictly necessary. Could be convinced either way.

**Comment by tomvannuenen** [comment]
Changed the name in notebook 5 to "How I Learned to Stop For-Looping and Love Vectorization" :)
