### ISSUE TITLE
Using dummified variables in 6

### ISSUE THREAD

**Issue by tomvannuenen** [dlab-berkeley/Python-Fundamentals#11]
Would there be a way to sensibly use the dummified variables of general health or poverty level in the visualization of correlations?

**Comment by pssachdeva** [comment]
Do we need to have this? I think this concept would be more appropriate for a machine learning workshop rather than a fundamentals series.

**Comment by tomvannuenen** [comment]
I think it could be valuable to introduce it to people who are using Pandas for their own data, but agree it does require some other methodological knowledge. Could we think of any other Pandas challenges that would make sense in the project?

**Comment by pssachdeva** [comment]
Some general ideas:
- Data cleaning or imputation. A column whose values are corrupted, or missing, and need to be fixed/replaced.
- Data cleaning with string functions (exposes attendees to the .str methods available in pandas). For example, having different values for education that need to be standardized.
- Bucketing values. For example, maybe we're interested in hispanic vs. non-hispanic folks. We'd need to mutate the ethnicity column into two values.
I'll keep thinking on other examples.

**Comment by tomvannuenen** [comment]
Great ideas. I've implemented the following:

- Inserted data cleaning.
- Drastically simplified dataset by removing unused variables. 
- Removed section on dummifying variables. 
- Altered fruit and vegetable columns to have a rough correlation and removing extreme outliers
- Added string methods

I'm still thinking of ways to connect the different skills we're testing into a more cohesive, logical, narrative thread. Which challenges could naturally succeed one another?
