### ISSUE TITLE
More EDA ideas for notebook 6

### ISSUE THREAD

**Issue by tomvannuenen** [dlab-berkeley/Python-Fundamentals#12]
Any other ideas for exploratory data analysis using the CHI data in the Final Project notebook are welcome!

**Comment by pssachdeva** [comment]
It would be nice to have a scatter plot. I tried looking at fruits per week vs. veg per week, but the plot was not informative. I also don't trust the values - there were many values above 20 for both axes in that plot.

One possibility would be to add fake columns that have some other data which we can scatter, or change the values or fruit/veg per week to look something roughly correlated.

**Comment by tomvannuenen** [comment]
Wouldn't a scatterplot with discrete variables be a bit confusing for some people? It's true the fruit and veg variables are a bit off, I can replace values over a certain threshold with new values w/ random noise.

**Comment by pssachdeva** [comment]
If there is a strong enough correlation, it won't really matter if its discrete. The relationship would be clear.

You could also make it continuous and just call it "average number of fruit per week".
