### ISSUE TITLE
Consistency in "Jupyter Notebook" vs "Jupyter notebook"

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/Python-Fundamentals#14]
Notebooks are referred to as both "Jupyter Notebooks" and "Jupyter notebooks". I think if notebook is used in the context of Jupyter it should be capitalized; i.e., "Jupyter Notebook" is always preferable. However, if we refer to the file as a "notebook", we do not need to capitalize it. Thoughts?

**Comment by tomvannuenen** [comment]
I think I prefer lowercasing when we're not talking about the Jupyter Notebook software but the file type. It's confusing either way however, so don't have strong opinions.

**Comment by pssachdeva** [comment]
I glanced at Jupyter's documentation, and they always refer to it as a "Jupyter Notebook", with N capitalized. In these cases, I usually defer to how the designers refer to their own product, so let's use "Jupyter Notebook".

**Comment by tomvannuenen** [comment]
Okay, will change.
