### ISSUE TITLE
Using code font to indicate user interface pathways

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/Python-Fundamentals#16]
It seems code font is used to indicate a UX pathway, e.g. `Kernel-> Restart` and `File -> Close and Shutdown Notebook`. I see one place where this doesn't happen (Edit -> Undo Cell Operation in the first notebook). Is this a style we want to enforce in the style guide?

**Comment by tomvannuenen** [comment]
Edited & added to style guide
