### ISSUE TITLE
Notebook 1: Need for indenting?

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/Python-Fundamentals#18]
Does indenting need to be in notebook 1? In the spirit of introducing things only when they're relevant, we could consider just removing that section until necessary (e.g. if statements, functions, etc.)

**Comment by tomvannuenen** [comment]
Not sure about this one – it seems like an important general concept (like commenting). If only introducing when it actually matters we won't cover it in fundamentals.. Thoughts?

**Comment by pssachdeva** [comment]
OK, let's just keep this in mind. If we feel like notebook 1 takes too long, this can be something that gets cut.
