### ISSUE TITLE
Notebook 2: Challenge 2

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/Python-Fundamentals#21]
"search enginge" -> "search engine"

**Comment by pssachdeva** [comment]
In that same challenge, `giraffe` is referenced, but I think it should be `country`.

**Comment by pssachdeva** [comment]
One more thing: the code block uses the `startswith()` function, but this needs an input? Shouldn't we use a function that doesn't need input? 

Perhaps we could have `country = 'grEEcE'`, and then do `country.lower().title()`.

**Comment by tomvannuenen** [comment]
Done.
