### ISSUE TITLE
Final Challenge (3-5)

### ISSUE THREAD

**Issue by tomvannuenen** [dlab-berkeley/Python-Fundamentals#24]
Moved Challenge 2-7(!) to Challenge 3-5. I think it's good to end with a challenge that makes them have to look something up on Google, in the spirit of ongoing active learning. I'm not sure if the challenge is relevant and at the right difficulty level. What do you think?

**Comment by pssachdeva** [comment]
This looks good. A couple changes:

* In point 2, you reference the `continent` column, but I think you mean `lifeExp`.
* I would directly reference subsetting by the `continent` column in point 1. That is, name the exact column to be as clear as possible.
