### ISSUE TITLE
fundamentals part 1

### ISSUE THREAD

**Issue by mmartinlopez** [dlab-berkeley/Python-Fundamentals#33]
Hi! I think it would be helpful if we could add pictures about what the different environments look like at the very beginning of the notebook. People opening it up on different environments (own computer vs datahub) had trouble finding buttons if they weren't using the same environment as the instructor.

**Comment by tomvannuenen** [comment]
@mml458 Do you mean the difference between Jupyter Lab and Jupyter Notebooks?
