### ISSUE TITLE
installation in readme

### ISSUE THREAD

**Issue by leahhrlee** [dlab-berkeley/Python-Fundamentals#44]
I think this line of code might not work:
From Readme:
Optional: if you're familiar with git, you can instead clone this repository by opening a terminal and entering git clone git@github.com:dlab-berkeley/Python-Fundamentals-I.git.

I think it should be:
git clone https://github.com/dlab-berkeley/Python-Fundamentals.git

**Comment by tomvannuenen** [comment]
edited
