### ISSUE TITLE
Learning about classes & methods

### ISSUE THREAD

**Issue by acgalvano** [dlab-berkeley/Python-Fundamentals#48]
Add resources for further learning about classes, how to create them and custom methods; mention if other workshops discuss this

**Comment by tomvannuenen** [comment]
@acgalvano custom functions are discussed in Python Fundamentals Part 4-6. We currently do not discuss Classes in our workshops.

**Comment by acgalvano** [comment]
@tomvannuenen Got it! This just came up when Taylor was introducing methods and students wanted to know if it was possible to create methods. I think one answer given was that you can define a new class and a method for it. None of the instructors knew if this would be covered in other workshops. Not sure if this is the best place for this kind of feedback, but Pratik said to be liberal about it :)

**Comment by tomvannuenen** [comment]
@acgalvano This is absolutely the right place, thanks! It's worth thinking about whether we want to add class creation somewhere in our workshops. I will add a sentence in the methods section saying it is possible but not covered here.
