### ISSUE TITLE
Review Part II

### ISSUE THREAD

**Issue by tomvannuenen** [dlab-berkeley/Python-Fundamentals#7]
Part II is ready for review.

**Comment by pssachdeva** [comment]
I pushed my changes. I think it looks good. I am still a little uncertain on whether it's possible to cover the material in 2 hours.  I am also not sure if the project needs a little bit more code support (e.g., some code filled out as opposed to empty cells to fill in).

I think both of these can best be answered with a pilot.

**Comment by tomvannuenen** [comment]
I agree and think we probably need to remove some material, particularly from lessons 4 and 5. I've tried keeping most things that were in the old PyFun, but I think it's too much, and not all of it is equally relevant for complete beginners. 

Happy to discuss which sections could potentially be cut.
Will add some code support in 6.

**Comment by tomvannuenen** [comment]
Pushed new version after discussion with Pratik on 12 Jan. Goal is to ensure notebooks can be covered in 2h each.

- Shortened notebooks 4 and 5, removing some duplicated sections.
- Changed Conditionals section in 4 to focus mostly on DataFrame operations
- Removed Matplotlib section in 5
- Rephrased and shortened some text
- Removed coding principles and strategies; these may be better suited for a new workshop (e.g. "Practical Tips for Data Science in Python"
